In [1]:
import numpy as np

In [2]:
a = np.array([[2,7,23], [0,1,2]], dtype=np.uint8)
a

array([[ 2,  7, 23],
       [ 0,  1,  2]], dtype=uint8)

In [3]:
b = np.unpackbits(a, axis=1)
b

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
        1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        1, 0]], dtype=uint8)

In [4]:
c = np.packbits(b,axis=1)

In [5]:
c

array([[ 2,  7, 23],
       [ 0,  1,  2]], dtype=uint8)